# Site
repository: hnishal/resume
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Himanshu
title: student/tech-enthusiast 
email: hnishal12799@gmail.com
contact: +917042306752
website: www.github.com/hnishal


# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  hnishal
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: himanshu-nishal-a348a5138
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000


# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Himanshu and I'm a UG student. Data-Science and Web-development are feilds i wanna excel in.I have an ample experience in competitive-coding. I have been a part of number group projects gaining teamwork and leadership skills.  
  I am most skilled in: <mark>Data-Science using R</mark> and <mark>Web-Development</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: freelancing website
        link: https://github.com/hnishal/website
        # link_text: Project Website
        additional_links:
          - title:  hnishal/website
            icon: fab fa-github
            url: https://github.com/hnishal/website
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is freelancing portal developed keeping in mind students
        description: | # this will include new lines to allow paragraphs
          This project uses <mark>React</mark> and <mark>React-bootstrap</mark> for its frontend. it is a user-friendly freelancing website. This website works with No-Sql database <mark>MongoDB</mark>, backend was coded in <mark>Python</mark>
      
      - layout: top-middle
        title: ecommerce website
        link: https://github.com/hnishal/website
        # link_text: Project Website
        additional_links:
          - title:  hnishal/website
            icon: fab fa-github
            url: https://github.com/hnishal/website
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is ecommerce website
        description: | # this will include new lines to allow paragraphs
          This is an Ecommerce website created using <mark>html</mark>, <mark>css</mark>, <mark>js</mark>, <mark>Sql</mark> and <mark>PHP</mark>. This is a simple ecommerce website with user-friendly frontend

  - title: Skills
    layout: list 
    content:
      - layout: left
        title: Programming Languages
        description:
        1. Html, css, java
        2. C++, Python, R
        
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Chandigarh University
        caption: 2019 - 2023
        sub_title: BE- Computer Science Engineering
        quote: >
          CGPA: 8.33

          
      - layout: left
        title: Kendriya Vidyalaya
        caption: 2017 - 2018
        sub_title: 12th Standard(CBSE)
        quote: >
          Percentage: 88%
          
      - layout: left
        title: Kendriya Vidyalaya
        caption: 2015 - 2016
        sub_title: 10th Standard(CBSE)
        quote: >
          CGPA: 10

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in devlopment and data science some of my other interests and hobbies are:
      - Going to the gym
      - Reading
      - Gaming


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
